name: To_release_project

on:
  push:
    branches:
      - feature
jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.4'
      - run: go version
      - name: Compile binary files for each platform.
        run: make
